### ISSUE TITLE
Add a README.md to describe the project

### ISSUE THREAD

**Issue by ras-drive** [ninjamuffin99/zero2prod#1]
A README.md file should be added to describe the project and what the main purpose of this repo is. A license should also be added, most likely MIT since this is a Rust project.

**Comment by ras-drive** [comment]
I am completely oblivious, I just saw that this is most likely your repo for the Rust Zero2Prod book and less of a full project. My fault I was just excited to maybe get in early to a project and help.

**Comment by ninjamuffin99** [comment]
haha lol its all good, yeah just gettin thru rust book and learnin 🙇‍♂️

maybe I'll write a readme anyways so other people lurkin around dont get confused hehehe
